const regions = {
    'Alabama': 'southwest',
    'Alaska': 'northwest',
    'Arizona': 'southwest',
    'Arkansas': 'southwest',
    'California': 'west',
    'Colorado': 'central',
    'Connecticut': 'east',
    'Delaware': 'east',
    'Florida': 'southwest',
    'Georgia': 'southwest',
    'Hawaii': 'southwest',
    'Idaho': 'northwest',
    'Illinois':' midwest',
    'Indiana': 'midwest',
    'Iowa': 'midwest',
    'Kansas': 'midwest',
    'Kentucky': 'midwest',
    'Louisiana': 'southwest',
    'Maine': 'east',
    'Maryland': 'east',
    'Massachusetts': 'east',
    'Michigan': 'midwest',
    'Minnesota': 'midwest',
    'Mississippi': 'southwest',
    'Missouri': 'midwest',
    'Montana': 'midwest',
    'Nebraska': 'midwest',
    'Nevada': 'southwest',
    'New Hampshire': 'east',
    'New Jersey': 'east',
    'New Mexico': 'southwest',
    'New York': 'east',
    'North Carolina': 'southwest',
    'North Dakota': 'midwest',
    'Ohio': 'midwest',
    'Oklahoma': 'midwest',
    'Oregon': 'northwest',
    'Pennsylvania': 'east',
    'Rhode Island': 'east',
    'South Carolina': 'southwest',
    'South Dakota': 'midwest',
    'Tennessee': 'midwest',
    'Texas': 'southwest',
    'Utah': 'west',
    'Vermont': 'east',
    'Virginia': 'east',
    'Washington': 'northwest',
    'West Virginia': 'east',
    'Wisconsin': 'midwest',
    'Wyoming': 'midwest'
}

export default regions;