/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-zpp-V-6DG3vCzpb47Ng6QP2IuHyTy9GFBpeamiek2bpKaU10G-ImW9dZpUir3B5lxa8C9dXKuuaYWqJofTHVEyANgHZOeYgVmMKjx0xxrv5vHRBl5KFPnxuw",
  "tt": "tt-1-7IJAEPyRkBgu1cB-fuoWHTzPNkmF8ia6suzkZv3xFt4=",
  "version": "2020-11-20"
}

export default ebconfig;